language: java
jdk:
  - openjdk7

before_script:
  - export PATH=$PATH:$PWD
  - wget http://build.berkeleybop.org/userContent/owltools/owltools -O owltools
  - wget http://build.berkeleybop.org/userContent/owltools/ontology-release-runner -O ontology-release-runner
  - wget http://build.berkeleybop.org/userContent/owltools/owltools-runner-all.jar -O owltools-runner-all.jar

# command to run tests
script: cd src/ontology && make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

