sudo: required

services:
  - docker
  
before_install:
  - docker pull obolibrary/osk

# command to run tests
script: cd src/ontology && ./run.sh make test

#after_success:
#  coveralls

notifications:
  email:
    - cjmungall@lbl.gov

